### ISSUE TITLE
Some bad last names in last_names.json file (data folder)

### ISSUE THREAD

**Issue by spetrik** [tooleks/shevchenko-js#116]
I found some bad chars in last_names.json file (data folder).
I made corrections:
- replaced some bad chars by correct one (see code below) 
        lastName = lastName.Replace("’", "'");
        lastName = lastName.Replace("l", "і");
        lastName = lastName.Replace("3", "з");
        lastName = lastName.Replace(",", "'");
- removes duplicates (ільченко, ісаєнко, лук'яненко, дем'яненко, григор'єва, григор'єв, дем'янчук, лук'янова, хом'як, затишняк, баб'як)
- do not include words with other bad chars (1099 'ы', 1101 'э', 1098 'ъ').
I got 99'902 correct last names. The original file has 99'922 last names.
I attached file with fixed last names.
[fixed_last_names.zip](https://github.com/tooleks/shevchenko-js/files/3413834/fixed_last_names.zip)

**Comment by tooleks** [comment]
@spetrik 

Thanks for your work!

I'll review your changes then add them to the next major release and close the issue.
