### ISSUE TITLE
Failed to parse sorce map

### ISSUE THREAD

**Issue by vmaksym** [tooleks/shevchenko-js#158]
Description: Got an error while run application: Failed to parse source map from  ... file: Error: ENOENT: no such file or directory.

Environment: React 18, typescript, create-react-app

**Comment by tooleks** [comment]
@vmaksym Fixed in `2.1.1`. Thanks for reporting!

Also, explicitly added `Anthroponym` and `Gender` types to public API, so now it's possible to use them in the client code:

```TypeScript
import { Anthroponym, Gender, inVocative } from 'shevchenko';

const anthroponym: Anthroponym = {
  gender: Gender.Male,
  firstName: 'Тарас',
  middleName: 'Григорович',
  lastName: 'Шевченко'
});

const result: Anthroponym = inVocative(anthroponym);;

console.log(result); // { gender: "male", firstName: "Тарасе", middleName: "Григоровичу", lastName: "Шевченку" }
```
