### ISSUE TITLE
Відмінювання прізвищ, які співпадають із загальним іменником

### ISSUE THREAD

**Issue by syevt** [tooleks/shevchenko-js#163]
Привіт) Думаю, тут англійською писати нема сенсу. Перш за все - класна ліба, зберегла мені купу часу, дякую! Побачив лише одну проблему: [тут](https://ukrainskamova.com/publ/ukrajinskij_pravopis_2007/pravopis_vlasnikh_prizvishh/vidminjuvannja_prizvishh/15-1-0-385) наполягають на тому, що "прізвища з закінченнями іменників II відміни відмінюються за зразками відмінювання відповідних іменників ІІ відміни", тобто родовий для "вітер", буде "вітру", хоча Дністер - Дністра. Тобто, виглядає так, що [цього](https://github.com/tooleks/shevchenko-js/blob/b39894b923abcff4a9372d0560edc4455eb761c4/src/resources/inflector/rules.json#L3914) рядка самого по собі недостатньо. Як варіант, можливо, має сенс додати словник із відмінами для кейсів, коли прізвище повністю співпадає з загальним іменником. Я б не сказав, що це таки issue, можна і закрити, якщо там потрібно додавати/міняти тону коду.

**Comment by tooleks** [comment]
Привіт @syevt , дякую за інтерес. Як я розумію, то тут є різниця в тому, чи ми відмінюємо прізвище, чи загальну назву.

> На відміну від однозвучних загальних назв, що мають у родовому відмінку однини закінчення **-у** **(-ю)**, прізвища в цьому відмінку закінчуються на **-а** **(-я)**: _Вітер_ – _Вітра_, _Мороз_ – _Мороза_, _Гай_ – _Гая_, _Галас_ – _Галаса_, _Мед_ – _Меда_.

Джерело: https://subject.com.ua/ukrmova/business/31.html (І.М. Плотницька, Ділова українська мова, 2008 – Розділ 3. Граматична парадигма самостійних частин мови в ділових паперах).

**Comment by syevt** [comment]
@tooleks ну значить, питання як мінімум дискусійне, так глибоко я, звісно, не копав. Дякую за лінку. Закриваю)
