### ISSUE TITLE
Додати чергування та спеціальні правила в іменниках II відміни

### ISSUE THREAD

**Issue by alexmarchenko** [tooleks/shevchenko-js#166]
Дякую за цю бібліотеку!

https://webpen.com.ua/pages/linguistic_norm/first_name_declination.html?
З розділу *Зауваження щодо відмінювання прізвищ іменникового типу ІІ відміни*:
> голосні о, е чергуються в закритому складі з і: Біловіл — Біловола, Сивокінь — Сивоконя, Кіт — Кота, Корінь — Кореня, Перебийніс — Перебийноса.
> АЛЕ в деяких прізвищах буква і зберігається й у відкритому складі: Куліш — Куліша (хоч куліш – кулешу), Кисіль — Кисіля (хоч кисіль – киселю), Чміль — Чміля, Чіп — Чіпа.

Наразі [демо](https://shevchenko-js.tooleks.com/?gender=male&lastName=%D0%9A%D0%B8%D1%81%D1%96%D0%BB%D1%8C&firstName=%D0%9E%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80&middleName=%D0%92%D1%96%D1%82%D0%B0%D0%BB%D1%96%D0%B9%D0%BE%D0%B2%D0%B8%D1%87) показує помилки в давальному відмінку для прізвищ *Куліш*, *Кисіль*
| Називний | Давальний зараз | Давальний має бути |
|----------|-----------------|--------------------|
| Куліш    | Кул**і**шу     | Кул**е**шу        |
| Кисіль   | Кис**і**лю      | Кис**е**лю         |

**Comment by tooleks** [comment]
@alexmarchenko Дякую за відгук!

Як я розумію, в даному правилі якраз описаний виняток, де "в деяких прізвищах буква і зберігається", тому Кул**і**ш — Кул**і**шу та Кис**і**ль — Кис**і**лю.

Наведені ж приклади у дужках, це приклади відмінювання відповідних іменників (не прізвищ, на що вказує написання з малої літери), де якраз підкреслюється виняток.

Я ще проконсультуюся з філологом, щодо цього питання. Відпишу про результат згодом.

**Comment by tooleks** [comment]
Додаю посилання на Український правопис 2019 року https://mon.gov.ua/storage/app/media/zagalna%20serednya/%202019.pdf (ст.135)

> Примітка 2. Усі чоловічі прізвища ІІ відміни в родовому відмінку мають
закінчення -а (-я) на відміну від деяких співвідносних загальних назв: пор. прізвища
Морóз — Морóз-а, Кулíш — Куліш-á, Коровáй — Коровá-я, Чорнотíнь — Чорнотíн-я,
Рись — Рúс-я і загальні назви морóз — морóз-у, кулíш — кулеш-ý, коровáй — коровá-ю,
тінь — тíн-і, рись — рúс-і.

Загальна назва кул**і**ш в родовому - кул**е**шу, а прізвище Кул**і**ш - Кул**і**ша.

**Comment by tooleks** [comment]
Після додаткової консультації підтвердив, що буква **і** зберігається у відкритому складі для прізвищ Куліш, Кисіль, Чміль, Чіп. Приклади з оригінального запитання в дужках, що подані з малої літери, це приклади відмінювання відповідних іменників загальних назв **в родовому** (не давальному) відмінку.

Наразі закриваю цей issue, дайте знати, якщо будуть додаткові питання.
