### ISSUE TITLE
Чи може ця бібліотека автоматично визначати стать?

### ISSUE THREAD

**Issue by rElectronik** [tooleks/shevchenko-js#167]
Вітаю!

Чи вміє дана бібліотека визначати стать? Якщо ні, то, чи планується додати такий функціонал?

Дякую!

**Comment by rElectronik** [comment]
> В найближчому часі не планується додавання такої функції, але якщо маєте якісь ідеї, то буду радий почути.

Дякую за відповідь. Ідеями навряд чи зможу допомогти, так як не є програмістом.

Але знайшов один схожий проект:
https://github.com/seagullua/NameCaseLib
Головна проблема в тому, що є помилкові відмінювання і, скорiш за все, вже не підтримується автором.

**Comment by rElectronik** [comment]
> Ви використовуєте веб інтерфейс для відмінювання? У вашому сценарії використання завжди є ім'я по батькові?

Так, використовую веб інтерфейс. 
Є різні сценарії:
ім’я + по батькові;
ім’я + прізвище;
прізвище + ім’я + по батькові.
Якщо вказують по батькові, то роблю перевірку через Excel за останнью літерою, якщо по батькові закінчується на "ч" у називному відмінку - чоловік, інакше - жінка.
І в кінці, якщо треба, роблю відмінювання у кличному відмінку.

**Comment by tooleks** [comment]
@rElectronik Зрозуміло, дякую за інформацію.

На даний момент я не розглядаю варіант додавання автоматичного визначення статі в саму бібліотеку, та для вашого сценарію використання додав опцію автоматичного визначення статі на веб-інтерфейс (див. опцію "Авто" на формі демонстрації відмінювання).

Автоматичне визначення статі використовує по батькові (класифікує за закінченням) або ж ім'я (шукає в словнику з 1155 найпоширеніших імен). Якщо ж стать визначити неможливо, показується помилка про необхідність ручного вибору статі.

Надіюсь, що це спростить вам роботу.

**Comment by rElectronik** [comment]
> @rElectronik Зрозуміло, дякую за інформацію.

Дякую за спілкування, неодмінно скористаюсь оновленим веб-інтерфейсом!
