### ISSUE TITLE
Auto gender

### ISSUE THREAD

**Issue by Triplecorpse** [tooleks/shevchenko-js#174]
Hi.
On the demo website there is an option to autoselect gender.
Is it possible to add this function to the package?

**Comment by tooleks** [comment]
Hello @Triplecorpse

I'm considering it right now. It doesn't work in 100% of cases. So I'm more in favor of exposing this functionality as a separate function.

Here is an example:

```JavaScript
const anthroponym = {
  firstName: 'Тарас',
  middleName: 'Григорович',
  lastName: 'Шевченко'
};

const gender = shevchenko.detectGender(anthroponym);
const result = shevchenko.inVocative({ gender, ...anthroponym });

console.log(result); // { gender: "male", firstName: "Тарасе", middleName: "Григоровичу", lastName: "Шевченку" }
```

I'll keep this issue opened for now to post any updates on this.

**Comment by Triplecorpse** [comment]
This code is not in main branch yet, right?
When is it expected to be merged?

**Comment by tooleks** [comment]
Sorry for the delay. It's now available in the feature release `v2.2.0`. The docs will be updated in the next major release.

**Comment by Triplecorpse** [comment]
@tooleks Hi. Are there any updates? I see you deployed v.3, I will upgrade if you say that auto gender is a feature now.

**Comment by tooleks** [comment]
Hey, @Triplecorpse

The grammatical gender detection feature is officially part of `v3` release. See the usage example: https://github.com/tooleks/shevchenko-js#automatic-grammatical-gender-detection. Be aware that **`v3` release has breaking changes**. See the migration guide for more details: https://github.com/tooleks/shevchenko-js/wiki/Migration-Guide

Also, if for some reason you don't want to migrate to `v3` but still want to take advantage of gender detection you may consider upgrading to `v2.2` as I mentioned in the comment above: https://github.com/tooleks/shevchenko-js/issues/174#issuecomment-1427528476
