### ISSUE TITLE
Cannot import library: getting 404

### ISSUE THREAD

**Issue by ostasevych** [tooleks/shevchenko-js#193]
When trying to execute ```npm install --save shevchenko.js```

I am getting the response:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/shevchenko.js - Not found
npm ERR! 404
npm ERR! 404  'shevchenko.js@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
Trying to proceed to the URL with the library in the npm registry I am getting 404 Not Found response:

![image](https://user-images.githubusercontent.com/5199030/230311659-e02e9584-725a-41cd-825a-ec2377778162.png)

**Comment by tooleks** [comment]
@ostasevych 

The command should be `npm install --save shevchenko` (without `.js`). It is already fixed on the website.

Thanks for your report.
