### ISSUE TITLE
Would that be possible to use shevchenko.js to apply declensions to country and city names?

### ISSUE THREAD

**Issue by abriginets** [tooleks/shevchenko-js#201]
I have a database of country and city names in ukrainian, but declension cases are missing there. I would like to add those declension cases to it, i.e.:

```json
  {
    "code": "SV",
    "name": "Сальвадор",
    "currency": "USD",
    "name_translations": { "en": "El Salvador" },
    "cases": {
      "давальний": "Сальвадору",
      "місцевий": "Сальвадорі",
      "родовий": "Сальвадора",
      "орудний": "Сальвадором",
      "знахідний": "у Сальвадор"
    }
  },
```

But I can't seems to make this library work with only `givenName`. Gender detection functionality fails and return null. Would that be possible to add declension cases for locations in this library?

**Comment by tooleks** [comment]
Unfortunately, that's not possible at the moment. The library lacks a proper grammatical gender detection module which is required for this use case. At the same time, I like the idea, so I'll keep the issue opened until I have more time to investigate.
