### ISSUE TITLE
redundant dependency?

### ISSUE THREAD

**Issue by skarbovskiy** [tooleks/shevchenko-js#203]
Does this package really need [this dep ](https://github.com/tooleks/shevchenko-js/blob/main/package.json#L52) to be populated in resulting package?
with all sub-deps it costs  276,4 MB of space.

**Comment by tooleks** [comment]
Short answer, yes.

The shevchenko library uses the TensorFlow module during runtime. If you're concerned about the size, you can often resolve it by tree-shaking the dead code of your output bundle using webpack, rollup, etc.

Additionally, there's a compact UMD bundle available. It's a single file that includes the library and its dependencies, taking up only 739 kB of space. You might want to give it a look.

![Screenshot from 2023-09-19 16-52-49](https://github.com/tooleks/shevchenko-js/assets/4424545/54929c18-c5e5-4273-92fd-c6ab5b38c11f)

Hope this helps. Let me know, if you have any other questions.
