### ISSUE TITLE
wrong invocation declension

### ISSUE THREAD

**Issue by skarbovskiy** [tooleks/shevchenko-js#204]
name: Артем
expected vocative: Артеме
actual vocative: Артему 

https://shevchenko-js.tooleks.com/en-US?gender=masculine&familyName=&givenName=%D0%90%D1%80%D1%82%D0%B5%D0%BC&patronymicName=

**Comment by tooleks** [comment]
Fixed in `v3.0.6`. Thanks for reporting!
